apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- poddefault-crd.yaml
- profile-crd.yaml
- notebooks-crd.yaml
- tensorboard-crd.yaml
- katib-crds.yaml
- training-operator-crds.yaml
- viewer-crd.yaml
- kserve-crds.yaml
- kserve-extra-crds.yaml
- metacontroller-crds.yaml
- argo-crds.yaml

commonLabels:
  app.kubernetes.io/part-of: kubeflow
  app.kubernetes.io/component: crds
