apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- upstream.yaml
- cert-manager.yaml
- grafana-virtualservice.yaml
- prometheus-virtualservice.yaml

patches:
- path: gateway-tls-patch.yaml
- path: delete-namespaces.yaml
